### ISSUE TITLE
ain't no party like a relying party

### ISSUE THREAD

**Issue by bc-pi** [hlflanagan/fedidcg#7]
There are a couple times prospective stakeholders are listed -- i.e., "needs of the user, the developer, and the identity provider"  and "to enable interoperability between user agents, developers, and identity providers." -- that seem to omit the relying party. Maybe developer was meant to encompass the RP? I dunno but user agents, IDPs and SPs all have developers.  Relying parties are fundamental to federated authentication and need to be given first class consideration. 

\* The t-shirt that inspired the issue title: https://www.flickr.com/photos/brian-d-campbell/51278659993

**Comment by hlflanagan** [comment]
I've updated this to "All work items from this community group must consider the needs of the user as well as the developers and operators for relying parties and identity providers"
